# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/voicelive/Azure.AI.VoiceLive

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: voicelive
    ArtifactName: packages
    Artifacts:
    - name: Azure.AI.VoiceLive
      safeName: AzureAIVoiceLive
